export const robots = [
  {
    id: 10,
    name: 'John Smith',
    username: 'JohnSmith',
    email: 'john.smith@gmail.com',
  },
  {
    id: 11,
    name: 'Mary Johnson',
    username: 'MaryJohnson',
    email: 'mary.johnson@gmail.com',
  },
  {
    id: 12,
    name: 'Michael Davis',
    username: 'MichaelDavis',
    email: 'michael.davis@gmail.com',
  },
  {
    id: 13,
    name: 'Sarah Wilson',
    username: 'SarahWilson',
    email: 'sarah.wilson@gmail.com',
  },
  {
    id: 14,
    name: 'David Brown',
    username: 'DavidBrown',
    email: 'david.brown@gmail.com',
  },
  {
    id: 15,
    name: 'Jennifer Taylor',
    username: 'JenniferTaylor',
    email: 'jennifer.taylor@gmail.com',
  },
  {
    id: 16,
    name: 'Matthew Clark',
    username: 'MatthewClark',
    email: 'matthew.clark@gmail.com',
  },
  {
    id: 17,
    name: 'Laura Martinez',
    username: 'LauraMartinez',
    email: 'laura.martinez@gmail.com',
  },
  {
    id: 18,
    name: 'Daniel Thomas',
    username: 'DanielThomas',
    email: 'daniel.thomas@gmail.com',
  },
  {
    id: 19,
    name: 'Emily Davis',
    username: 'EmilyDavis',
    email: 'emily.davis@gmail.com',
  },
  {
    id: 20,
    name: 'Christopher Andy',
    username: 'ChrisAnderson',
    email: 'chris.anderson@gmail.com',
  },
  {
    id: 21,
    name: 'Jessy Thompson',
    username: 'JessicaThompson',
    email: 'jessica.thompson@gmail.com',
  },
  {
    id: 22,
    name: 'Brian Moore',
    username: 'BrianMoore',
    email: 'brian.moore@gmail.com',
  },
  {
    id: 23,
    name: 'Kimberly Lewis',
    username: 'KimLewis',
    email: 'kimberly.lewis@gmail.com',
  },
  {
    id: 24,
    name: 'Alex Harris',
    username: 'AlexHarris',
    email: 'alex.harris@gmail.com',
  },
];
